all:
	gcc simple_shell_script.c -o simple_shell_script
	gcc  fib.c -o fib
	gcc helloworld.c -o helloworld
	chmod +x shellscript.sh

run:
	./simple_shell_script
	
clean:
	@rm -f fib helloworld shellscript simple_shell_script