all:
	chmod +x fib.c
	chmod +x simple_scheduler.c
	gcc simple_scheduler.c -o simple_scheduler
	gcc fib.c -o fib
	gcc helloworld.c -o helloworld
	gcc apple.c -o apple
	

clean:

	@rm simple_scheduler fib helloworld apple